global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus-main:9090

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor-main:8080

  - job_name: airflow
    metrics_path: /metrics
    static_configs:
      - targets:
          - airflow:8080
